# For more information, see https://github.com/gerukin/ai-tester/tree/main/docs

candidatesTemperature: 0.3
candidates:
  - provider: ollama
    model: phi4:14b-q4_K_M
  - provider: openai
    model: gpt-4o-mini-2024-07-18
  - provider: vertex
    model: gemini-1.5-flash-002

attempts: 1

requiredTags1:
  - lang_en

requiredTags2:
  - off_topic
  - reasoning
  - math

evaluatorsTemperature: 0.5
evaluationsPerEvaluator: 2
evaluators:
  - provider: ollama
    model: gemma2:9b-instruct-q4_K_M
  - provider: ollama
    model: mistral-nemo:12b-instruct-2407-q4_K_M
  - provider: ollama
    model: phi4:14b-q4_K_M
  - provider: openai
    model: gpt-4o-mini-2024-07-18
  - provider: vertex
    model: gemini-1.5-flash-002
